Repository junyeong237/spring_dp, pull requests merged in 2023-12, with the labels that each got.

#1 Feat : 공용 TimeEntity 추가
  src/main/java/com/example/dp/domain/model/TimeEntity.java
Labels: enhancement

#10 Feat/user
  src/main/java/com/example/dp/domain/user/UserRole.java
  src/main/java/com/example/dp/domain/user/controller/UserController.java
  src/main/java/com/example/dp/domain/user/dto/request/UserSignUpRequest.java
  src/main/java/com/example/dp/domain/user/entity/User.java
  src/main/java/com/example/dp/domain/user/repository/UserRepository.java
  src/main/java/com/example/dp/domain/user/service/UserService.java
Labels: feat

#14 Feat/add order entity
  src/main/java/com/example/dp/domain/order/entity/Order.java
  src/main/java/com/example/dp/domain/order/entity/OrderMenu.java
  src/main/java/com/example/dp/domain/order/entity/OrderStateEnum.java
Labels: enhancement

#19 [#18] Feature/jasypt
  build.gradle
  src/main/java/com/example/dp/global/config/JasyptConfig.java
  src/test/java/com/example/dp/global/config/JasyptConfigTest.java
Labels: feat, test, chore

#23 Feat/add cart cud
  src/main/java/com/example/dp/domain/cart/dto/request/CartRequestMenuDto.java
  src/main/java/com/example/dp/domain/cart/dto/response/CartResponseDto.java
  src/main/java/com/example/dp/domain/cart/entity/Cart.java
  src/main/java/com/example/dp/domain/cart/repository/CartRepository.java
  src/main/java/com/example/dp/domain/cart/service/CartService.java
  src/main/java/com/example/dp/domain/cart/service/impl/CartServiceImpl.java
  src/main/java/com/example/dp/domain/menu/entity/Menu.java
  src/main/java/com/example/dp/domain/order/entity/Order.java
Labels: feat

#25 [#24] Feature/review create
  build.gradle
  src/main/java/com/example/dp/domain/order/repository/OrderRepository.java
  src/main/java/com/example/dp/domain/review/controller/ReviewController.java
  src/main/java/com/example/dp/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/example/dp/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/example/dp/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/dp/domain/review/service/ReviewService.java
  src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/example/dp/domain/review/validator/ReviewValidator.java
  src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
  src/test/resources/application.yml
Labels: feat, test, chore

#29 Refactor : import url 주소 변경
  src/main/java/com/example/dp/domain/cart/controller/CartController.java
Labels: fix

#32 Test/add test redis
  .gitignore
  build.gradle
  src/test/java/com/example/dp/TestRedisConfiguration.java
  src/test/resources/application.yml
Labels: test, chore

#36 [#35]Feature/review update - 리뷰 수정
  src/main/java/com/example/dp/domain/review/controller/ReviewController.java
  src/main/java/com/example/dp/domain/review/entity/Review.java
  src/main/java/com/example/dp/domain/review/service/ReviewService.java
  src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/example/dp/domain/review/validator/ReviewValidator.java
  src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
Labels: feat, test

#44 Refactor/user
  src/main/java/com/example/dp/domain/user/controller/UserController.java
  src/main/java/com/example/dp/domain/user/dto/request/UserLoginRequestDto.java
  src/main/java/com/example/dp/domain/user/service/UserService.java
  src/main/java/com/example/dp/domain/user/service/impl/UserLogoutImpl.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/dp/global/config/WebSecurityConfig.java
  src/main/java/com/example/dp/global/redis/RedisConfig.java
  src/main/java/com/example/dp/global/redis/RedisUtil.java
  src/main/java/com/example/dp/global/security/JwtAuthenticationFilter.java
  src/main/java/com/example/dp/global/security/JwtAuthorizationFilter.java
  src/main/java/com/example/dp/global/security/UserDetailsImpl.java
Labels: feat, refactor, rename

#41 [#40] Feature/review delete
  src/main/java/com/example/dp/domain/order/entity/Order.java
  src/main/java/com/example/dp/domain/review/controller/ReviewController.java
  src/main/java/com/example/dp/domain/review/service/ReviewService.java
  src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
  src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
Labels: feat, test

#45 Feat/add order create
  .gitignore
  src/main/java/com/example/dp/domain/order/controller/OrderController.java
  src/main/java/com/example/dp/domain/order/dto/response/OrderResponseDto.java
  src/main/java/com/example/dp/domain/order/dto/response/OrderSimpleResponseDto.java
  src/main/java/com/example/dp/domain/order/entity/Order.java
  src/main/java/com/example/dp/domain/order/repository/OrderRepository.java
  src/main/java/com/example/dp/domain/order/service/OrderService.java
  src/main/java/com/example/dp/domain/order/service/impl/OrderServiceImpl.java
  src/main/java/com/example/dp/domain/ordermenu/entity/OrderMenu.java
  src/main/java/com/example/dp/domain/ordermenu/repository/OrderMenuRepository.java
  src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
Labels: enhancement, feat

#55 Refactor : Category, Menu 수정
  src/main/java/com/example/dp/domain/admin/controller/AdminMenuController.java
  src/main/java/com/example/dp/domain/admin/service/impl/AdminMenuServiceImpl.java
  src/main/java/com/example/dp/domain/category/controller/CategoryController.java
  src/main/java/com/example/dp/domain/category/dto/request/CategoryRequestDto.java
  src/main/java/com/example/dp/domain/category/entity/Category.java
  src/main/java/com/example/dp/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/dp/domain/menu/dto/request/MenuRequestDto.java
  src/main/java/com/example/dp/domain/menu/entity/Menu.java
  src/test/java/com/example/dp/domain/category/service/impl/CategoryServiceImplTest.java
Labels: refactor

#56 Fix : MenuDetailResponseDto 수정
  src/main/java/com/example/dp/domain/menu/dto/response/MenuDetailResponseDto.java
Labels: fix

#59 Feature : Category 삭제시 포함된 메뉴가 없는지 체크
  src/main/java/com/example/dp/domain/category/entity/Category.java
  src/main/java/com/example/dp/domain/category/exception/CategoryErrorCode.java
  src/main/java/com/example/dp/domain/category/exception/ForbiddenDeleteCategory.java
  src/main/java/com/example/dp/domain/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/dp/domain/menucategory/repository/MenuCategoryRepository.java
Labels: feat

#74 Feature/admin review - 어드민 리뷰 삭제 기능
  src/main/java/com/example/dp/domain/admin/controller/AdminReviewController.java
  src/main/java/com/example/dp/domain/admin/service/AdminReviewService.java
  src/main/java/com/example/dp/domain/admin/service/impl/AdminReviewServiceImpl.java
  src/test/java/com/example/dp/domain/admin/service/impl/AdminReviewServiceImplTest.java
Labels: feat, test

#71 Feature/menu read like - 좋아요 기준으로 메뉴 조회 기능 구현
  src/main/java/com/example/dp/domain/menu/controller/MenuController.java
  src/main/java/com/example/dp/domain/menu/service/MenuService.java
  src/main/java/com/example/dp/domain/menu/service/impl/MenuServiceImpl.java
  src/main/java/com/example/dp/domain/menulike/entity/MenuLike.java
  src/main/java/com/example/dp/domain/menulike/repository/MenuLikeRepository.java
  src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
Labels: feat, test, rename

#83 Feature/admin user read 관리자 사용자 조회 구현
  src/main/java/com/example/dp/domain/admin/controller/AdminUserController.java
  src/main/java/com/example/dp/domain/admin/service/AdminUserService.java
  src/main/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImpl.java
  src/main/java/com/example/dp/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/dp/domain/user/exception/NotFoundUserException.java
  src/main/java/com/example/dp/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/dp/domain/user/repository/UserRepository.java
  src/test/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImplTest.java
  src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
  src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
  src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
  src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
Labels: feat, test

#89 Feature/profile image - 사용자 프로필 이미지 수정/삭제
  src/main/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImpl.java
  src/main/java/com/example/dp/domain/review/exception/NotFoundUserException.java
  src/main/java/com/example/dp/domain/review/service/impl/ReviewServiceImpl.java
  src/main/java/com/example/dp/domain/user/controller/UserController.java
  src/main/java/com/example/dp/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/dp/domain/user/entity/User.java
  src/main/java/com/example/dp/domain/user/service/UserService.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/dp/global/config/WebSecurityConfig.java
  src/main/java/com/example/dp/global/s3/AwsS3Util.java
  src/main/java/com/example/dp/global/s3/exception/AwsS3ErrorCode.java
  src/main/java/com/example/dp/global/s3/exception/AwsS3InternalException.java
  src/test/java/com/example/dp/domain/admin/service/impl/AdminReviewServiceImplTest.java
  src/test/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImplTest.java
  src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
  src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
  src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
  src/test/resources/application.yml
Labels: feat, test, style, chore

#91 Feature/ 메뉴에 이미지 추가한 CUD 구현 & Admin User 구현
  src/main/java/com/example/dp/domain/admin/controller/AdminMenuController.java
  src/main/java/com/example/dp/domain/admin/controller/AdminUserController.java
  src/main/java/com/example/dp/domain/admin/service/AdminMenuService.java
  src/main/java/com/example/dp/domain/admin/service/AdminUserService.java
  src/main/java/com/example/dp/domain/admin/service/impl/AdminMenuServiceImpl.java
  src/main/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImpl.java
  src/main/java/com/example/dp/domain/menu/dto/response/MenuDetailResponseDto.java
  src/main/java/com/example/dp/domain/menu/dto/response/MenuSimpleResponseDto.java
  src/main/java/com/example/dp/domain/menu/entity/Menu.java
  src/main/java/com/example/dp/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/example/dp/domain/user/UserStatus.java
  src/main/java/com/example/dp/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/dp/domain/user/entity/User.java
  src/main/java/com/example/dp/domain/user/exception/BlockedUserException.java
  src/main/java/com/example/dp/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/dp/domain/user/service/UserService.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/dp/global/security/JwtAuthenticationFilter.java
  src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
  src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
Labels: feat, refactor

#93 Feature/mail code
  src/main/java/com/example/dp/domain/authemail/entity/AuthEmail.java
  src/main/java/com/example/dp/domain/authemail/exception/AuthEmailErrorCode.java
  src/main/java/com/example/dp/domain/authemail/exception/UnauthenticatedAuthEmailException.java
  src/main/java/com/example/dp/domain/authemail/repository/AuthEmailRepository.java
  src/main/java/com/example/dp/domain/authemail/service/AuthEmailService.java
  src/main/java/com/example/dp/domain/authemail/service/impl/AuthEmailServiceImpl.java
  src/main/java/com/example/dp/domain/user/constant/UserConstant.java
  src/main/java/com/example/dp/domain/user/controller/UserController.java
  src/main/java/com/example/dp/domain/user/dto/UserCheckCodeRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/request/UserCheckCodeRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/request/UserSendMailRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/response/UserCheckCodeResponseDto.java
  src/main/java/com/example/dp/domain/user/exception/UnauthorizedEmailException.java
  src/main/java/com/example/dp/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/dp/domain/user/service/UserService.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/dp/global/config/MailConfig.java
  src/main/java/com/example/dp/global/config/RedisConfig.java
  src/main/java/com/example/dp/global/infra/mail/exception/ExpiredCodeException.java
  src/main/java/com/example/dp/global/infra/mail/exception/MailErrorCode.java
  src/main/java/com/example/dp/global/infra/mail/service/impl/MailServiceImpl.java
  src/test/java/com/example/dp/DpApplicationTests.java
Labels: feat, refactor, rename

#96 Feature/profile
  src/main/java/com/example/dp/domain/user/controller/UserController.java
  src/main/java/com/example/dp/domain/user/dto/request/UserDeleteRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/request/UserIntroduceMessageUpdateRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/request/UserPasswordUpdateRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/request/UsernameUpdateRequestDto.java
  src/main/java/com/example/dp/domain/user/dto/response/UserIntroduceMessageUpdateResponseDto.java
  src/main/java/com/example/dp/domain/user/dto/response/UserPasswordUpdateResponseDto.java
  src/main/java/com/example/dp/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/dp/domain/user/dto/response/UsernameUpdateResponseDto.java
  src/main/java/com/example/dp/domain/user/entity/User.java
  src/main/java/com/example/dp/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/dp/domain/user/exception/VerifyPasswordException.java
  src/main/java/com/example/dp/domain/user/service/UserService.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
Labels: feat

#97 Refactor/user domain
  src/main/java/com/example/dp/domain/admin/service/impl/AdminUserServiceImpl.java
  src/main/java/com/example/dp/domain/order/service/impl/OrderServiceImpl.java
  src/main/java/com/example/dp/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/example/dp/domain/user/entity/User.java
  src/main/java/com/example/dp/domain/user/entity/UserRole.java
  src/main/java/com/example/dp/domain/user/entity/UserStatus.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/example/dp/global/config/WebSecurityConfig.java
  src/main/java/com/example/dp/global/security/UserDetailsImpl.java
  src/test/java/com/example/dp/domain/cart/CartIntegrationTest.java
  src/test/java/com/example/dp/domain/menu/service/impl/MenuServiceImplTest.java
  src/test/java/com/example/dp/domain/order/OrderIntegrationTest.java
  src/test/java/com/example/dp/domain/review/service/impl/ReviewServiceImplTest.java
Labels: rename

#99 Feature/password history
  src/main/java/com/example/dp/domain/user/authemail/entity/AuthEmail.java
  src/main/java/com/example/dp/domain/user/authemail/exception/AuthEmailErrorCode.java
  src/main/java/com/example/dp/domain/user/authemail/exception/UnauthenticatedAuthEmailException.java
  src/main/java/com/example/dp/domain/user/authemail/repository/AuthEmailRepository.java
  src/main/java/com/example/dp/domain/user/authemail/service/AuthEmailService.java
  src/main/java/com/example/dp/domain/user/authemail/service/impl/AuthEmailServiceImpl.java
  src/main/java/com/example/dp/domain/user/exception/PasswordRestrictionException.java
  src/main/java/com/example/dp/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/dp/domain/user/password/dto/response/PasswordHistoryResponseDto.java
  src/main/java/com/example/dp/domain/user/password/entity/PasswordHistory.java
  src/main/java/com/example/dp/domain/user/password/repository/PasswordHistoryRepository.java
  src/main/java/com/example/dp/domain/user/password/service/PasswordHistoryService.java
  src/main/java/com/example/dp/domain/user/password/service/impl/PasswordHistoryServiceImpl.java
  src/main/java/com/example/dp/domain/user/service/impl/UserServiceImpl.java
Labels: feat, rename
